#ifndef PAGENUMBER_HPP
#define PAGENUMBER_HPP

enum PageNumbers {
    EXIT_PAGE = 9,
    HERO_PHASE_PAGE = 0,
    MOVE_PAGE = 1,
    GUIDE_PAGE = 2,
    PICKUP_PAGE = 3,
    ADVANCED_PAGE = 4,
    DEFEAT_PAGE = 5,
    SPECIALACTION_PAGE = 6,
    PLAYPERK_PAGE = 7,
    HELP_PAGE = 8,
    MONSTERPHASE_PAGE = 10,
    WELCOME_PAGE = 11,
    PLAYER_SETUP_PAGE = 12,
    HERO_SELECTION_PAGE = 13,
    LOAD_MATCH_PAGE = 14,
    SAVE_MODE = 15
};

#endif